import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import AuthProvider from "./auth/Provider";
import "./globals.css";
import Navbar from "./Navbar";
import 'ldrs/grid';


// const roboto = Roboto({ subsets: ['latin'], weight: ['400', '500'] });
const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '600']
})
export const metadata: Metadata = {
  title: 'My Next App',
  description: 'Generated by create next app',
  openGraph: {
    title: 'My Next App',
    description: 'Generated by create next app',
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="mytheme">
      <head>
        <script type="module" src="https://cdn.jsdelivr.net/npm/ldrs/dist/auto/grid.js" defer></script>
      </head>
      <body className={poppins.className}>
        <AuthProvider>
          <Navbar />
          <main className='p-5'>
            {/* <Suspense fallback={<l-grid size="60" speed="1.5" color="black"></l-grid>}> */}
            {children}
            {/* </Suspense> */}
          </main>
        </AuthProvider>
      </body>
    </html>
  );
}
